### ISSUE TITLE
Error Sign

### ISSUE THREAD

**Issue by guidsribeiro** [catppuccin/gitea#1]
![image](https://user-images.githubusercontent.com/61317250/227066820-5a22a919-403f-47cc-875b-07fd9582fa77.png)

**Comment by guidsribeiro** [comment]
Hello! No reviewers?

**Comment by nekowinston** [comment]
Hi, this repo is just for tracking the issues with the Gitea theme itself, not our instance :slightly_smiling_face: 

We currently only accept org members into our Gitea instance, sorry about that.

**Comment by guidsribeiro** [comment]
> Hi, this repo is just for tracking the issues with the Gitea theme itself, not our instance 🙂
> 
> We currently only accept org members into our Gitea instance, sorry about that.

Oh, ok. Thks
