### ISSUE TITLE
Header/Navbar Remains Light/White Regardless of the theme applied?

### ISSUE THREAD

**Issue by jontstaz** [catppuccin/gitea#11]
Hi,

I seemingly successfully added all the Catppuccin themes to my app.ini and restarted my Gitea instance. I also set the default theme to `catppuccin-frappe-blue`. However no matter what catppuccin theme I set it to, the navbar/header remains white/light for some reason.

Screenshots:
![image](https://github.com/catppuccin/gitea/assets/6379873/41dd4ab3-248a-4ab7-99ce-168989445dc0)
![image](https://github.com/catppuccin/gitea/assets/6379873/8412e69b-eb82-4a7d-a93b-312e935160ae)
![image](https://github.com/catppuccin/gitea/assets/6379873/892df61a-5a2c-4e54-82d4-8737ffc153a3)

I'm super confused. Any help would be appreciated. Thanks,

**Comment by blacknet76** [comment]
@jontstaz you can change the following in the .css files to make it display correctly:

search for:
```
  --color-nav-bg: 
  --color-nav-bg-transparent:
```

and replace it with 
```
  --color-nav-bg: 
  --color-nav-hover-bg: 
```

I am not a profi and have only been using the theme since yesterday, so I don't know if the behaviour is correct.
