### ISSUE TITLE
1.21 Support

### ISSUE THREAD

**Issue by LimePotato** [catppuccin/gitea#19]
Latest forgejo/gitea update completely breaks the themes, showing a light theme instead
![image](https://github.com/catppuccin/gitea/assets/9313366/fe8b43cd-5e36-46d9-a133-bdc57f08492d)

**Comment by isabelroses** [comment]
> Latest forgejo/gitea update completely breaks the themes, showing a light theme instead

That's likely since the css directory moved to `$GITEA_CUSTOM/public/assets/css` from the previous `$GITEA_CUSTOM/public/css`
