### ISSUE TITLE
Is there a way to make this work for forgejo?

### ISSUE THREAD

**Issue by h4rldev** [catppuccin/gitea#22]
I was wondering if I could make this work for forgejo, when I apply any mocha theme it seems to just make forgejo light theme

**Comment by justTOBBI** [comment]
It should work for forgejo, a friend of mine hosts an instance with the mocha theme applied. Make sure you set all variables and stuff. Sorry I cannot help further :)

**Comment by h4rldev** [comment]
Yeah, It's in public/assets/css, but it doesn't apply still

**Comment by h4rldev** [comment]
Yeah It sends 404s in the networking tab, idk why

**Comment by h4rldev** [comment]
it's in the gitea/public/assets/css folder

**Comment by h4rldev** [comment]
it was user error, ignore this catppuccin.
