### ISSUE TITLE
What do I put in my app.ini?

### ISSUE THREAD

**Issue by FormalSnake** [catppuccin/gitea#3]
I want to apply the macchiato theme, but I don't know the theme name for the config.

**Comment by rubyowo** [comment]
if you've named the theme file as `catppuccin-macchiato.theme` you'd use the theme as "catppuccin-macchiato"

**Comment by isabelroses** [comment]
The themes should be replaced to all the themes that you installed. And `DEFAULT_THEME` is the default theme that you want.
```
[ui]
catppuccin-frappe-blue,catppuccin-frappe-flamingo,catppuccin-frappe-green,catppuccin-frappe-lavender,catppuccin-frappe-maroon,catppuccin-frappe-mauve,catppuccin-frappe-peach,catppuccin-frappe-pink,catppuccin-frappe-red,catppuccin-frappe-rosewater,catppuccin-frappe-sapphire,catppuccin-frappe-sky,catppuccin-frappe-teal,catppuccin-frappe-yellow,catppuccin-latte-blue,catppuccin-latte-flamingo,catppuccin-latte-green,catppuccin-latte-lavender,catppuccin-latte-maroon,catppuccin-latte-mauve,catppuccin-latte-peach,catppuccin-latte-pink,catppuccin-latte-red,catppuccin-latte-rosewater,catppuccin-latte-sapphire,catppuccin-latte-sky,catppuccin-latte-teal,catppuccin-latte-yellow,catppuccin-macchiato-blue,catppuccin-macchiato-flamingo,catppuccin-macchiato-green,catppuccin-macchiato-lavender,catppuccin-macchiato-maroon,catppuccin-macchiato-mauve,catppuccin-macchiato-peach,catppuccin-macchiato-pink,catppuccin-macchiato-red,catppuccin-macchiato-rosewater,catppuccin-macchiato-sapphire,catppuccin-macchiato-sky,catppuccin-macchiato-teal,catppuccin-macchiato-yellow,catppuccin-mocha-blue,catppuccin-mocha-flamingo,catppuccin-mocha-green,catppuccin-mocha-lavender,catppuccin-mocha-maroon,catppuccin-mocha-mauve,catppuccin-mocha-peach,catppuccin-mocha-pink,catppuccin-mocha-red,catppuccin-mocha-rosewater,catppuccin-mocha-sapphire,catppuccin-mocha-sky,catppuccin-mocha-teal,catppuccin-mocha-yellow
DEFAULT_THEME  = catppuccin-mocha-sapphire```

**Comment by FormalSnake** [comment]
Thanks for the quick answer!
I put that in /data/gitea/conf/app.ini, but the theme does not seem to work

I put the css files in /data/gitea/public/css
Am I doing something wrong?

**Comment by isabelroses** [comment]
> Thanks for the quick answer! I put that in /data/gitea/conf/app.ini, but the theme does not seem to work

You need to restart the instance of gitea.

**Comment by FormalSnake** [comment]
when I press update theme after selection, the selection becomes blank and the theme does not change.

**Comment by isabelroses** [comment]
> when I press update theme after selection, the selection becomes blank and the theme does not change.

Can we see any logs? I'm not to sure what could be wrong from just that since that is what happens when the themes are misconfigured.

**Comment by FormalSnake** [comment]
[_kyan_git_logs.txt](https://github.com/catppuccin/gitea/files/11360956/_kyan_git_logs.txt)

**Comment by isabelroses** [comment]
> [_kyan_git_logs.txt](https://github.com/catppuccin/gitea/files/11360956/_kyan_git_logs.txt)

its trying to apply `theme-macchiato` so I'm guessing that's the name of the CSS file, however it cannot be found so you might want to check your `public/css/` folder to see the names there and ensure they are the exact same same they are in the `app.ini` without the following `.css`

**Comment by FormalSnake** [comment]
It looks great now! Thanks for the help!
