### ISSUE TITLE
line highlighting is broken

### ISSUE THREAD

**Issue by isabelroses** [catppuccin/gitea#36]
`Forgejo version: 8.0.1 built with go1.22.5`

See image below:
![image](https://github.com/user-attachments/assets/c6ca49ec-34d7-47bd-9768-8574ad38b364)

[reproduction url](https://git.isabelroses.com/isabel/dotfiles/src/commit/88f8445be88ec9b667a6f6a7115f830e28aa2678/parts/programs/pre-commit.nix#L32)

**Comment by uncenter** [comment]
Variable in question is `--color-highlight-bg`. Not sure what was theming it before...
