### ISSUE TITLE
Inline code in titles is black/not readable

### ISSUE THREAD

**Issue by Zk2u** [catppuccin/gitea#51]
![Screenshot 2024-11-02 at 10 28 19](https://github.com/user-attachments/assets/6ff211b4-b81a-4a3e-9ebe-dbb265bf6a2a)

I presume the text should be white

**Comment by sgoudham** [comment]
Hey :wave:,

What version of Gitea are you running? `gitea.catppuccin.com` is running on 1.22 at the moment and it seems to be highlighted correctly:

https://gitea.catppuccin.com/catppuccin/nix/commit/32359bf226fe874d3b7a0a5753d291a4da9616fe
![image](https://github.com/user-attachments/assets/bf42ddec-fcd2-4b56-9c2f-6466b7811296)

**Comment by sgoudham** [comment]
Ah okay interesting. I'll close this issue as resolved but feel free to re-open if you're seeing the same behaviour on `1.22`!
