### ISSUE TITLE
Unlegible text in some areas with mocha theme

### ISSUE THREAD

**Issue by myNicole98** [catppuccin/gitea#7]
![image](https://github.com/catppuccin/gitea/assets/74139268/61d1ae97-da0b-417a-a5b0-b3ec6a241589)
![image](https://github.com/catppuccin/gitea/assets/74139268/c585b9dc-0102-44bc-af85-71c911078c5d)

**Comment by nekowinston** [comment]
Hey there!
Could you please add some info about which version of Gitea you're running and where exactly those issues show up?
From what I can see, our instance doesn't have these issues: [[1]](https://gitea.catppuccin.com/catppuccin/deepl) [[2]](https://gitea.catppuccin.com/explore/repos)

**Comment by myNicole98** [comment]
I'm running the latest version of Gitea on docker, you can take a look at gitea.nikko.cf
The theme I'm using is mocha-lavender.
The issues appear when looking at a repo and when browsing a user profile

**Comment by nekowinston** [comment]
Closed after we figured out that this was caused by this instance being Gitea 1.17.3. Gitea 1.18 is the minimum supported version for this theme.

Thanks for helping to figure this out!
