### ISSUE TITLE
Too bright ;w;

### ISSUE THREAD

**Issue by BiscuitEat2r** [catppuccin/gitea#8]
I really like this theme, but the selected line is too bright when editing code I hope it can be made a bit darker qwq
especially maroon( really like it

**Comment by nekowinston** [comment]
![2023-08-22-150004@2x](https://github.com/catppuccin/gitea/assets/79978224/2c7e4869-a355-4b93-b3f9-fe3e84ace5d7)
![2023-08-22-150026@2x](https://github.com/catppuccin/gitea/assets/79978224/df7eb456-62da-4e76-adb1-78340bfdf5dd)
